const Letters = {
    "\u2764": "_heart.jpg",
    _space: ["_space_blue.jpg", "_space_green.jpg", "_space_red.jpg", "_space_yellow.jpg"],
    "!": "_bang.jpg",
    ",": "_comma.jpg",
    ".": "_period.jpg",
    "'": "_apostrophe.jpg",
    "’": "_apostrophe.jpg",
    "*": "_astersk.jpg",
<<<<<<< HEAD
    "@": "_at.jpg",
    "&": "_ampersand.jpg",
    "$": "_dollar.jpg",
    "%": "_percent.jpg",
=======
    "#": "_octothorpe.jpg",
    "“": "_left_quote.jpg",
    "”": "_right_quote.jpg",
    "?": "_question.jpg",
>>>>>>> 8c66432ca64a5b64ec4865d274157a2a39fb96de
    A: "A.jpg",
    B: "B.jpg",
    C: "C.jpg",
    D: "D.jpg",
    E: "E.jpg",
    F: "F.jpg",
    G: "G.jpg",
    H: "H.jpg",
    I: "I.jpg",
    J: "J.jpg",
    K: "K.jpg",
    L: "L.jpg",
    M: "M.jpg",
    N: "N.jpg",
    O: "O.jpg",
    P: "P.jpg",
    Q: "Q.jpg",
    R: "R.jpg",
    S: "S.jpg",
    T: "T.jpg",
    U: "U.jpg",
    V: "V.jpg",
    W: "W.jpg",
    X: "X.jpg",
    Y: "Y.jpg",
    Z: "Z.jpg",
    "0": "0.jpg",
    "1": "1.jpg",
    "2": "2.jpg",
    "3": "3.jpg",
    "4": "4.jpg",
    "5": "5.jpg",
    "6": "6.jpg",
    "7": "7.jpg",
    "8": "8.jpg",
    "9": "9.jpg"
};

module.exports = Letters;

