const Letters = {
    "\u2764": "_heart.jpg",
    _space: ["_space_blue.jpg", "_space_green.jpg", "_space_red.jpg", "_space_yellow.jpg"],
    "!": "_bang.jpg",
    ",": "_comma.jpg",
    ".": "_period.jpg",
    "'": "_apostrophe.jpg",
    "’": "_apostrophe.jpg",
    "*": "_astersk.jpg",
    A: "A.jpg",
    B: "B.jpg",
    C: "C.jpg",
    D: "D.jpg",
    E: "E.jpg",
    F: "F.jpg",
    G: "G.jpg",
    H: "H.jpg",
    I: "I.jpg",
    J: "J.jpg",
    K: "K.jpg",
    L: "L.jpg",
    M: "M.jpg",
    N: "N.jpg",
    O: "O.jpg",
    P: "P.jpg",
    Q: "Q.jpg",
    R: "R.jpg",
    S: "S.jpg",
    T: "T.jpg",
    U: "U.jpg",
    V: "V.jpg",
    W: "W.jpg",
    X: "X.jpg",
    Y: "Y.jpg",
    Z: "Z.jpg"
};

module.exports = Letters;

